import './globals.css'
import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import { ThemeProvider } from '@/components/providers/theme-provider'

const font = Open_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Team chat application',
  description: 'Generated by Bahar Keshavarz',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
     <ClerkProvider>
        <html lang="en" suppressHydrationWarning>
            <ThemeProvider
                 attribute="class"
                 defaultTheme="dark"
                 enableSystem
                 storageKey="discord-theme"
              >
               <body className={font.className}>
                {children}
             </body>
            </ThemeProvider>
        </html>
     </ClerkProvider>
  )
}
